name: pikanrt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.15
  - pip=24.2
  - pandas=2.2.3
  - pyyaml=6.0.1
  - matplotlib=3.9.2
  - pytorch=2.4.1
  - torchvision=0.19.1
  - cudatoolkit=11.8.0
  - scikit-learn=1.5.2
  - notebook=7.2.2
  - enlighten=1.12.4
  - plotly=5.24.1
  - seaborn=0.13.2
  - pip:
    - git+https://github.com/Blealtan/efficient-kan.git
    - pykan==0.2.8
